service: lambda-web-service

provider:
  name: aws
  runtime: java11
  profile: lambda-profile
  timeout: 10
  memorySize: 1024
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::lambda-custom-bucket'
        - !Join ['', ['arn:aws:s3:::', !Ref ServerlessDeploymentBucket, '/*']]

custom:
  myBucket: lambda-custom-bucket

package:
  artifact: target/Lamda_Web_service-0.0.1-SNAPSHOT.jar

functions:
  simpleLambda:
    handler: com.lamda.service.Lamda_Web_service.lambda.User
    environment:
      MESSAGE: Duke42
  requestPost:
    handler: com.lamda.service.Lamda_Web_service.lambda.requestPostHandler
    events:
      - http:
          method: POST
          path: /users/1/requests

  donationPost:
    handler: com.lamda.service.Lamda_Web_service.lambda.donationPostHandler
    events:
      - http:
        method: POST
        path: /users/1/donations

    donationGet:
      handler: com.lamda.service.Lamda_Web_service.lambda.donationGetHandler
      events:
        - http:
          method: GET
          path: /users/1/donations



